name: Build Check on PR

on:
    pull_request:
        branches: [main, test]

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout test
              uses: actions/checkout@v3
              with:
                  ref: test
            - name: Build
              run: /bin/sh deploy.sh
