name: Deploy to EC2 usinf AWS SSM Send-Command

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v2

            - name: Install Dependencies
              run: npm install
            - name: Build
              run: npm run build
    Deploy:
        runs-on: ubuntu-22.04
        needs: build
        steps:
            - uses: actions/checkout@v2

            - name: AWS SSM Send-Command
              uses: peterkimzz/aws-ssm-send-command@master
              with:
                  aws-region: ${{ secrets.AWS_REGION }}
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  instance-ids: ${{ secrets.INSTANCE_ID }}

                  working-directory: /home/ubuntu/
                  comment: Hello world!
                  command: /bin/sh ./deploy.sh

            - name: Get the outputs
              run: echo "The Command id is ${{ steps.ssm.outputs.command-id }}"
